steps:
- id: 'admin dependency'
  name: node:10.15.3
  entrypoint: npm
  dir: 'admin'
  args: ['install']
- id: 'application dependency'
  name: node:6.10
  entrypoint: npm
  args: ['install']
- id: 'workers dependency'
  name: node:6.10
  entrypoint: npm
  dir: 'workers'
  args: ['install']
- id: 'notification dependency'
  name: node:8.16
  entrypoint: npm
  dir: 'notification-service'
  args: ['install']
- id: 'all-services-up'
  name: docker/compose:1.24.0
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    docker-compose -f docker-e2e-compose.yml up -d
  waitFor: ['admin dependency','application dependency','workers dependency', 'notification dependency']
- name: node:6.10
  id: Run-e2e-tests
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd /workspace/
    npm install -g bower grunt-cli protractor
    sleep 60
    protractor ./e2e/conf.js --baseUrl http://web:3000 --verbose
  waitFor: ['all-services-up']
timeout: 12600s