#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  GITFLOW_COMMAND="git flow"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  GITFLOW_COMMAND="git-flow"
fi
RELEASE_VERSION=$(grep version package.json | head -1 | tr -s ' ' | awk '{ print $2 }' | sed 's/[",]//g' | sed 's/-.*//g')
echo "It is assumed that you have merged your changes into develop branch."
echo "Creating a release branch release/$RELEASE_VERSION from develop branch"
git checkout develop
${GITFLOW_COMMAND} release start v${RELEASE_VERSION}

editor=${EDITOR:-vim}
echo "Update version in package.json"
$editor package.json

echo "Update version in npm-shrinkwrap.json"
$editor npm-shrinkwrap.json

echo "Write release notes in CHANGELOG.txt"
$editor CHANGELOG.txt

git diff
echo "Verify changes before commit. Exit the shell to commit changes"
$SHELL || true
git commit -a -m "Bump ${RELEASE_VERSION}" --signoff --no-verify


echo "Push branch to docker remote"
${GITFLOW_COMMAND} release publish v${RELEASE_VERSION}
