#!/bin/bash

function lib_error() {
  #statements
  echo -e "$(tput setaf 1)$@$(tput sgr0)"
	exit $2
}

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  GITFLOW_COMMAND="git flow"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  GITFLOW_COMMAND="git-flow"
fi
RELEASE_VERSION=$(grep version package.json | head -1 | tr -s ' ' | awk '{ print $2 }' | sed 's/[",]//g' | sed 's/-.*//g')
${GITFLOW_COMMAND} release finish v${RELEASE_VERSION} || lib_error "\tIssue occured while publishing commits to master branch. \n\tAfter you resolve issue run following command to finish release. \n\t\t# git checkout master && git push\n\t\t# git push --tags " $?
git checkout master && git push || lib_error "\tIssue occured while publishing commits to master branch. \n\tAfter you resolve issue run following command to finish release. \n\t\t# git checkout master && git push\n\t\t# git push --tags " $?
git push --tags
