ALTER TABLE dbo.HSPRODUCTSYNCTABLEStaging add STOCKUPTRANSFERTIME DATETIME, STOCKUPTRANSFER INT;
ALTER TABLE dbo.EcoResProductV2Staging add STOCKUPTRANSFERTIME DATETIME, STOCKUPTRANSFER INT;
ALTER TABLE dbo.HSInventDimStaging add STOCKUPTRANSFERTIME DATETIME, STOCKUPTRANSFER INT;
ALTER TABLE dbo.HSInventSumStaging add STOCKUPTRANSFERTIME DATETIME, STOCKUPTRANSFER INT;
ALTER TABLE dbo.RetailTransactionSalesLineStaging add STOCKUPTRANSFERTIME DATETIME, STOCKUPTRANSFER INT;
ALTER TABLE dbo.RetailTransactionStaging add STOCKUPTRANSFERTIME DATETIME, STOCKUPTRANSFER INT;
