on:
  push:
    branches:
      - master
      - develop
      - 'release/v[0-9].[0-9]+.[0-9]+'

jobs:
  build_dev:
    name: dev
    runs-on: ubuntu-latest
    if:
      contains('
        refs/heads/develop
        ', github.ref)
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: build docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: stockup
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:dev-${GITHUB_SHA::8} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-${GITHUB_SHA::8}

  build_release:
    name: releases
    runs-on: ubuntu-latest
    if:
      contains(
        github.ref,
        'refs/heads/release/v'
        )
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: build docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: stockup
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:staging-${GITHUB_SHA::8} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:staging-${GITHUB_SHA::8}

  build_prod:
    name: production
    runs-on: ubuntu-latest
    if:
      contains('
      refs/heads/master
      ',github.ref)
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: build docker images
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: stockup
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:production-${GITHUB_SHA::8} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:production-${GITHUB_SHA::8}